name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust targets
        run: |
          rustup target add aarch64-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu

      - name: Install Zig and cargo-zigbuild
        run: |
          brew install zig
          cargo install cargo-zigbuild

      - name: Build binaries
        run: make build-parallel-all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/parallel-arm64
            dist/parallel-amd64
            install.sh
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
